### ISSUE TITLE
How to make the Paste_images_in_SE_sites.user.js run in Firefox?

### ISSUE THREAD

**Issue by ooker777** [Darker/userscripts#2]
Hello, I would like to know how to make it run. I'm not a programmer and I know nothing about JS. I read somewhere that you can run the JS by execute it on Scratchpad. But when I do, an error appears:

```
/*
Exception: missing ; before statement
@Scratchpad/1:10
*/
```

What should I do? Or can you zip it to an addon? Thank you.

**Comment by Darker** [comment]
Hello.
Userscript is a script that runs in the browser the same way, and with same privileges as scripts on webpages.

Generally, every browser may have different approach to run userscripts. But in fact, it's just as simple as installing add-on that allows you to run userscripts, then install any scripts you want to use (or write your own if you can).

Please read [this guide that will help you to install userscripts in your browser](https://greasyfork.org/cs/help/installing-user-scripts). Note that I found this entering "_how to install userscripts all browsers_" in google.

If you run in another problems let me know after you're sure you've done everything right.

**Comment by ooker777** [comment]
Thank you Darker. It works. I know that I should search for solution by Google first, I just don't know that I should use the _userscript_ keyword.

**Comment by Darker** [comment]
I consider this closed then. Have a nice day :)
