### ISSUE TITLE
Are you still accepting pull requests?

### ISSUE THREAD

**Issue by GaurangTandon** [Darker/userscripts#3]
I found your wonderful StackPaste userscript and wished to submit a couple of improvements to the code. Considering that this repo has been inactive for over four years now, I wish to ask if you are still actively looking for pull requests/would accept one if I submit it after testing it?

**Comment by Darker** [comment]
I wanted to update that script for a long time, but couldn't make myself to dig in the code. If you're willing to dig through my garbage code, I'll be more than happy to accept a pull request.

**Comment by GaurangTandon** [comment]
Sorry...I tried but I unfortunately give up midway. There's too much stuff going on and increasingly hard to make sense of what method is trying to do what. My final state was when I successfully removed a few redundant methods and comments, used proper `debugLog`s to minimize comments, and used a `Map` of `<input>`s and their `EditorControler`s...

Feel free to merge it if you wish to.
